<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Client\Controller\IndexController' => __DIR__ . '/src/Client/Controller/IndexController.php',
    'Client\Module'                     => __DIR__ . '/Module.php',
);
