<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Market\Controller\IndexController' => __DIR__ . '/src/Market/Controller/IndexController.php',
    'Market\Module'                     => __DIR__ . '/Module.php',
    'MarketTest\SampleTest'             => __DIR__ . '/tests/Market/SampleTest.php',
    'MarketTest\Framework\TestCase'     => __DIR__ . '/tests/Market/Framework/TestCase.php',
);
